version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # Use the appropriate Node.js version for your project
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running tests..."
      - npm test  # Optional: run tests if you have them set up

  build:
    commands:
      - echo "Building the project..."
      - npm run build  # Use `npm start` if you don't have a build script

  post_build:
    commands:
      - echo "Starting the application..."
      - npm start  # Start the application

artifacts:
  files:
    - '**/*'  # Include all files in the build output (optional)
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
