version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # Adjust the Node.js version if needed
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running tests..."
      - npm test  # Optional if tests are set up

  build:
    commands:
      - echo "Building the project..."
      - npm run build  # Corrected command

  post_build:
    commands:
      - echo "Starting the application..."
      - npm start  # Start the app if necessary
